export const SHEET_ID =
"14T7zF0likp8YGeycOYBcOs9INY9gvMzpt7SMfghE8P4";

export const TABS = [
{
    id:"veiculos",
    title:"VEÍCULOS",
    sheet:"VEÍCULOS",
    headers:[
        "Placa",
        "Status",
        "Odômetro",
        "Combustível"
    ]
},
{
    id:"motoristas",
    title:"MOTORISTAS",
    sheet:"MOTORISTAS",
    headers:[
        "Motorista",
        "Status",
        "Condição"
    ]
},
{
    id:"painel",
    title:"PAINEL",
    sheet:"LANÇAMENTOS",
    headers:[
        "Data",
        "Hora",
        "Empregado",
        "Veículo",
        "Passageiro/Setor/Motivo",
        "Itinerário",
        "Status"
    ]
}
];
